<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5VHKQUJ" failures="0" tests="3" name="com.ae.qa.testcasesWorkflowAdmin.CategoriesPageTestWA" time="87.898" errors="1" timestamp="01 Feb 2023 10:10:38 GMT" skipped="0">
  <testcase classname="com.ae.qa.testcasesWorkflowAdmin.CategoriesPageTestWA" name="endReport" time="18.789">
    <error message="javax.mail.AuthenticationFailedException: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [PN3PR01CA0141.INDPRD01.PROD.OUTLOOK.COM 2023-02-01T10:10:38.627Z 08DB03F1A67AC312]
" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: javax.mail.AuthenticationFailedException: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [PN3PR01CA0141.INDPRD01.PROD.OUTLOOK.COM 2023-02-01T10:10:38.627Z 08DB03F1A67AC312]

at com.ae.qa.util.SendMail.sendExtentReport(SendMail.java:79)
at com.ae.qa.base.TestBase.endReport(TestBase.java:218)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.139 Authentication unsuccessful, the user credentials were incorrect. [PN3PR01CA0141.INDPRD01.PROD.OUTLOOK.COM 2023-02-01T10:10:38.627Z 08DB03F1A67AC312]

at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:965)
at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:876)
at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:780)
at javax.mail.Service.connect(Service.java:388)
at javax.mail.Service.connect(Service.java:246)
at javax.mail.Service.connect(Service.java:195)
at javax.mail.Transport.send0(Transport.java:254)
at javax.mail.Transport.send(Transport.java:124)
at com.ae.qa.util.SendMail.sendExtentReport(SendMail.java:76)
... 25 more
]]>
    </error>
  </testcase> <!-- endReport -->
  <testcase classname="com.ae.qa.testcasesWorkflowAdmin.CategoriesPageTestWA" name="ValidateAssignWFToCategoryWATest" time="38.911"/>
  <testcase classname="com.ae.qa.testcasesWorkflowAdmin.CategoriesPageTestWA" name="ValidateRemoveWFFromCategoryWATest" time="30.198"/>
</testsuite> <!-- com.ae.qa.testcasesWorkflowAdmin.CategoriesPageTestWA -->
